### ISSUE TITLE
Structures with same name and different InChiKey in JUMP-Target 2

### ISSUE THREAD

**Issue by dkuhn** [jump-cellpainting/JUMP-Target#24]
There are some compounds that have the same name/smiles but different InChiKey. I think that only the first InChiKey in the list should be used and the metada file should be adapted. Will create a new one with created/matched JUMPCP identifier. 

dexamethasone | UREBDLICKHMUKA-QCYOSJOCSA | NUREBDLICKHMUKA-CXSFZGCWSA-N
thiostrepton      | NSFFHOGKXHRQEW-DVRIZHICSA | NNSFFHOGKXHRQEW-AIHSUZKVSA-N
BVT-948            | LLPBUXODFQZPFH-UHFFFAOYSA  | NAJVXVYTVAAWZAP-UHFFFAOYSA-N

**Comment by niranjchandrasekaran** [comment]
Hi @dkuhn, thanks for confirming this. @shntnu had also noticed this previously (https://github.com/jump-cellpainting/JUMP-Target/issues/9).

> Will create a new one with created/matched JUMPCP identifier.

That would be great to have. Thanks!
