### ISSUE TITLE
Missing `broad_sample` IDs in ORF and CRISPR platemap files

### ISSUE THREAD

**Issue by jenna-tomkinson** [jump-cellpainting/JUMP-Target#29]
# Problem

When connecting the plate map files and metadata files, we find that there are missing broad_sample IDs in all plate maps, causing single cells to have no metadata (when processing with pycytominer).

When looking at the documentation in the main README, we find that there are 4 "empty" wells from each of these experiments:

![image](https://github.com/jump-cellpainting/JUMP-Target/assets/107513215/85826cba-8b45-4634-87d3-00135c56925a)

But, the term empty is not defined. We had assumed it meant there were no cells so the well is empty. But, we find that plates from these experiments do infact contain single cells as morphology features were extracted.

# Question

@gwaybio let us know that this probably indicates not that the well is empty of cell, but is empty of treatment. 

**Can you confirm that this is correct and `empty` is synonymous with `no treatment?`**

If so, we would be able to get around the missing metadata issue by including a fake broad_sample ID to these wells so that the single cell data is not removed during processing.

**Comment by niranjchandrasekaran** [comment]
Hi @jenna-tomkinson, your understanding is correct. `empty` is synonymous with `no treatment` in the ORF and CRISPR platemaps. Using a fake ID is a good workaround.

**Comment by jenna-tomkinson** [comment]
@niranjchandrasekaran 

Thank you so much for the confirmation!
