### ISSUE TITLE
Identify JUMP IDs for Target-2 compounds

### ISSUE THREAD

**Issue by goncinious** [jump-cellpainting/JUMP-Target#35]
I'm struggling to find the corresponding JUMP IDs for all the 306 (+1 with DMSO) compounds present in the Target-2 plates.

My approach so far was to join the [Target-2 compound metadata table](https://github.com/jump-cellpainting/JUMP-Target/blob/master/JUMP-Target-2_compound_metadata.tsv) with [JUMP's compound metadata](https://github.com/jump-cellpainting/datasets/blob/main/metadata/compound.csv.gz) by `InChIKey` to obtain the `Metadata_JCP2022` for these. However, 125/307 of the `InChIKey`s aren't in the JUMP's compound table. Attached is a CSV of the compounds missing.

[target2_not_in_jump.csv](https://github.com/jump-cellpainting/JUMP-Target/files/14921760/target2_not_in_jump.csv)
![image](https://github.com/jump-cellpainting/JUMP-Target/assets/25257793/da23ddf9-c8f0-4746-b9a1-edba1a9d9cc5)

Are these `InChIKey`s expected to be found in the JUMP's compound or perhaps there's a better approach to obtain the JUMP IDs?

**Comment by niranjchandrasekaran** [comment]
Hi @goncinious, we just updated the metadata file (in the `fix-target2-columns` branch). If you use the `InChIKey_standardized` column in [that file](https://github.com/jump-cellpainting/JUMP-Target/blob/900d0fab6c1c5770a8936d5c88ef6f7a1bd2faae/JUMP-Target-2_compound_metadata.tsv), you should be able to map them to the `InChIKey`s in the JUMP compound dataset. Please let us know if this doesn't work.

**Comment by goncinious** [comment]
Thanks you - that's sorted 👍🏼

**Comment by goncinious** [comment]
> If you use the InChIKey_standardized column in [that file](https://github.com/jump-cellpainting/JUMP-Target/blob/900d0fab6c1c5770a8936d5c88ef6f7a1bd2faae/JUMP-Target-2_compound_metadata.tsv)

Just to note that the column is named `InChIKey` and not `InChIKey_standardized` in the table in `fix-target2-columns` branch.
